imflipPMC	: imflipPMC.c ImageStuff.c ImageStuff.h
			  gcc imflipPMC.c ImageStuff.c -o imflipPMC -lpthread

imrotateMMC	: imrotateMMC.c ImageStuff.c ImageStuff.h
			  gcc imrotateMMC ImageStuff.c -o imrotateMMC -lpthread -lr
